#!/usr/bin/env bash

################################# GLOBAL VARS
DEBIAN_ISO="https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.6.0-amd64-netinst.iso"
MACHINE_NAME=$1


##################################### START FUNCTIONS
# verify if image debian os exists
# parameters:
#   $DEBIAN_ISO
VERIFY_DEBIAN_OS_EXIST() {
    # Download debian.iso
    if [ ! -f ./debian.iso ]; then
        wget "$DEBIAN_ISO" -O debian.iso
    fi
}

# create a new virtual machine
# parameters:
#   $MACHINE_NAME
#
# commands:
#   pwd
CREATE_VIRTUAL_MACHINE() {
    #Create VM
    VBoxManage createvm --name "$MACHINE_NAME" --ostype "Debian_64" --register --basefolder "$(pwd)"
}

# set memory and network in virtual machine
# parameters:
#   $MACHINE_NAME
SET_MEMORY_NETWORK() {
    #Set memory and network
    VBoxManage modifyvm "$MACHINE_NAME" --ioapic on
    VBoxManage modifyvm "$MACHINE_NAME" --memory 512 --vram 128
    VBoxManage modifyvm "$MACHINE_NAME" --nic1 nat
}

# create a disk hard size in the new virtual machine
# parameters:
#   $MACHINE_NAME
#
# commands:
#   pwd
CREATE_DISK_STORAGE() {
    #Create Disk and connect Debian Iso
    VBoxManage createhd --filename "$(pwd)"/"$MACHINE_NAME"/"$MACHINE_NAME_DISK".vdi --size 5000 --format VDI
}

# set storage controller and connect disk hard of controller in vm
# parameters:
#   $MACHINE_NAME
#
# commands:
#   pwd
SET_STORAGE_CONTROLLER() {
    # create sata controller
    VBoxManage storagectl "$MACHINE_NAME" --name "SATA Controller" --add sata --controller IntelAhci

    # connect hard disk to the vm from the sata controller
    VBoxManage storageattach "$MACHINE_NAME" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "$(pwd)"/"$MACHINE_NAME"/"$MACHINE_NAME_DISK".vdi

    # create ide controller
    VBoxManage storagectl "$MACHINE_NAME" --name "IDE Controller" --add ide --controller PIIX4

    # connect hard disk to the vm from the ide controller
    VBoxManage storageattach "$MACHINE_NAME" --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium "$(pwd)"/debian.iso

    # set boot type first iso and then from hard drive
    VBoxManage modifyvm "$MACHINE_NAME" --boot1 dvd --boot2 disk --boot3 none --boot4 none
}

# enable RDP ( remote desktop protocol )
# parameters:
#   $MACHINE_NAME
ENABLE_REMOTE_DESKTOP_PROTOCOL() {
    #Enable RDP ( enable remote desktop protocol support )
    VBoxManage modifyvm "$MACHINE_NAME" --vrde on
    VBoxManage modifyvm "$MACHINE_NAME" --vrdemulticon on --vrdeport 10001
}

# start vm in background ( headless )
# parameters:
#   $MACHINE_NAME
START_VM_IN_BACKGROUND() {
    #Start the VM
    VBoxHeadless --startvm "$MACHINE_NAME"
}
######################################################## END FUNCTIONS

######################################################## PRINCIPAL PROGRAM
MAIN() {
    VERIFY_DEBIAN_OS_EXIST & wait
    CREATE_VIRTUAL_MACHINE & wait
    SET_MEMORY_NETWORK & wait
    CREATE_DISK_STORAGE & wait
    SET_STORAGE_CONTROLLER & wait
    ENABLE_REMOTE_DESKTOP_PROTOCOL & wait
    START_VM_IN_BACKGROUND
}
