#!/bin/bash

source ./vbox_functions.sh

#Time method
start_date=$(date +%s)
reboot_date=0
minutes=0

#Control variables
reboot_count=0
server_down_start=0

#reboot types
force=0
soft=0
ssh=0

#checks if date A is greater than date B
function is_date_greater() {
  now=$(date +%s)
  if [ "$now" -ge "$1" ]; then
    echo 1
  else
    echo 0
  fi
}

#checks if $1 is a number
function is_number() {
  local re='^[0-9]+$'
  if ! [[ $1 =~ $re ]]; then
    return 1
  fi
  return 0
}

function print_usage() {
  echo "script usage $(basename "$0")  [-t <integer> minutes] [-m <integer> mb] [-p (TODO)] [-f (forced reboot)] [-s (soft reboot)] [-ssh (ssh reboot)]" >&1
}

if [[ "$1" =~ ^((-{1,2})([Hh]$|[Hh][Ee][Ll][Pp])|)$ ]]; then
  print_usage
  exit 0
else
  while [[ $# -gt 0 ]]; do
    opt="$1"
    shift
    current_arg="$1"
    if [[ "$current_arg" =~ ^-{1,2}.* ]]; then
      echo "WARNING: You may have left an argument blank. Double-check your command."
      exit 1
    fi
    case "$opt" in
    "-t" | "--time")
      minutes=$1
      reboot_date=$(date -d "($start_date) +$1 mins" +%s)
      echo "Iniciando testes de rejuvenescimento | A MV irá reinciar a cada $minutes minutos"
      shift
      ;;
    "-f" | "--force")
      force=1
      shift
      ;;
    "-s" | "--soft")
      soft=1
      shift
      ;;
    "-ssh" | "--ssh")
      ssh=1
      shift
      ;;
    "-n" | "--name")
      vm_name="$1"
      shift
      ;;
    "-h" | "--help")
      print_usage
      exit 0
      ;;
    *)
      echo "ERROR: Invalid option: \"$opt\"" >&2
      print_usage
      exit 1
      ;;
    esac
  done
fi

function VERIFY_SERVER_STATUS() {
  if [ "$server_down_start" -ne "0" ]; then
    code=$(curl -w "%{http_code}" -o /dev/null -s "http://localhost:8080")
    if [ "$code" -eq 200 ]; then
      date_time=$(date +%d-%m-%Y-%H:%M:%S)
      server_down_end=$(date +%s)
      result="$((server_down_end - server_down_start))"
      server_down_start=0

      echo "$date_time; $reboot_count; $result" >>logs/server_status.csv
      echo "Server is up again"
    fi
  fi
}

function REBOOT_VM() {
  ((reboot_count++))
  server_down_start=$(date +%s)
  if [ "$soft" -eq 1 ]; then
    GRACEFUL_REBOOT
  fi

  if [ "$ssh" -eq 1 ]; then
    SSH_REBOOT
  fi

  if [ "$force" -eq 1 ]; then
    FORCED_REBOOT
  fi
}

START_VM

./workload.sh disks/disk 50 &
./machine_resources_monitoring/run &

while true; do
  :
  date_time=$(date +%d-%m-%Y-%H:%M:%S)
  result=$(is_date_greater $reboot_date)
  if [ "$result" -eq 1 ]; then
    REBOOT_VM
  fi

  VERIFY_SERVER_STATUS

  sleep 1
done
