#!/bin/bash

# Lista de URLs para download
urls=(
    "https://www.dropbox.com/scl/fi/4kl5hxy6ftiwbcqly8ca0/debian4gb.tar?rlkey=2klw6giva484pdzc5o2kiqsfq&dl=0"
    "https://www.dropbox.com/scl/fi/4kl5hxy6ftiwbcqly8ca0/debian4gb.tar?rlkey=2klw6giva484pdzc5o2kiqsfq&dl=0"
    "https://www.dropbox.com/scl/fi/4kl5hxy6ftiwbcqly8ca0/debian4gb.tar?rlkey=2klw6giva484pdzc5o2kiqsfq&dl=0"
    "https://www.dropbox.com/scl/fi/4kl5hxy6ftiwbcqly8ca0/debian4gb.tar?rlkey=2klw6giva484pdzc5o2kiqsfq&dl=0"
    "https://www.dropbox.com/scl/fi/4kl5hxy6ftiwbcqly8ca0/debian4gb.tar?rlkey=2klw6giva484pdzc5o2kiqsfq&dl=0"
    "https://www.dropbox.com/scl/fi/4kl5hxy6ftiwbcqly8ca0/debian4gb.tar?rlkey=2klw6giva484pdzc5o2kiqsfq&dl=0"
    "https://www.dropbox.com/scl/fi/4kl5hxy6ftiwbcqly8ca0/debian4gb.tar?rlkey=2klw6giva484pdzc5o2kiqsfq&dl=0"
    "https://www.dropbox.com/scl/fi/4kl5hxy6ftiwbcqly8ca0/debian4gb.tar?rlkey=2klw6giva484pdzc5o2kiqsfq&dl=0"
    "https://www.dropbox.com/scl/fi/4kl5hxy6ftiwbcqly8ca0/debian4gb.tar?rlkey=2klw6giva484pdzc5o2kiqsfq&dl=0"
    "https://www.dropbox.com/scl/fi/4kl5hxy6ftiwbcqly8ca0/debian4gb.tar?rlkey=2klw6giva484pdzc5o2kiqsfq&dl=0"
)

count=1

# Loop para baixar cada arquivo
for url in "${urls[@]}"; do
    echo $count > file_count
    wget -O arquivo.tar "$url" > /dev/null
    rm -rf arquivo.tar
    count=$((count+1))
done

