#!/bin/bash

function headers() {
  mkdir -p logs
  echo "usr;nice;sys;iowait;soft;date_time" >logs/monitoramento-cpu.csv
  echo "used;date_time" >logs/monitoramento-disco.csv
  echo "used;cached;buffer;swap-free;date_time" >logs/monitoramento-mem.csv
  echo "num_zumbis;date_time" >logs/monitoramento-zumbis.csv
  echo "num_zumbis;date_time" >logs/monitoramento-zumbis.csv
}

headers

while true; do
  :
  date_time=$(date +%d-%m-%Y-%H:%M:%S)

  source machine-resources/monitoramento-cpu.sh
  source machine-resources/monitoramento-disco.sh
  source machine-resources/monitoramento-mem.sh
  source machine-resources/monitoramento-zumbis.sh
  source machine-resources/monitoramento-cores.sh

  sleep 1
done